app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  api-link:
    git-hub: https://api.github.com
    stack-overflow: https://api.stackexchange.com/2.3
    bot: ${BOT_BASE_URL:http://localhost:8090}
  debug-information:
    api-error-response-stack-trace-list-length: 5

spring:
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
